name: Lint

on:
  push:
    paths:
      - "**.py"
      - "**.pyi"
      - ".github/workflows/lint.yml"
  pull_request:
    paths:
      - "**.py"
      - "**.pyi"
      - ".github/workflows/lint.yml"
  workflow_dispatch:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
